import styles from '../scss/Calculator.module.scss';

const Buttons = (props) => {
	return (
		<div className={styles.buttons}>
			<div className={styles.calculation__buttons}>
				<button
					id='seven'
					value='7'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					7
				</button>
				<button
					id='eight'
					value='8'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					8
				</button>
				<button
					id='nine'
					value='9'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					9
				</button>
				<button
					id='delete'
					onClick={props.onDel}
					className={styles.secondary__button}
				>
					Del
				</button>
				<button
					id='four'
					value='4'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					4
				</button>
				<button
					id='five'
					value='5'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					5
				</button>
				<button
					id='six'
					value='6'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					6
				</button>
				<button
					id='add'
					value='+'
					onClick={props.onSignClick}
					className={styles.primary__button}
				>
					+
				</button>
				<button
					id='one'
					value='1'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					1
				</button>
				<button
					id='two'
					value='2'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					2
				</button>
				<button
					id='three'
					value='3'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					3
				</button>
				<button
					id='subtract'
					value='-'
					onClick={props.onSignClick}
					className={styles.primary__button}
				>
					-
				</button>
				<button
					id='decimal'
					value='.'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					.
				</button>
				<button
					id='zero'
					value='0'
					onClick={props.onCalcClick}
					className={styles.primary__button}
				>
					0
				</button>
				<button
					id='divide'
					value='/'
					onClick={props.onSignClick}
					className={styles.primary__button}
				>
					/
				</button>
				<button
					id='multiply'
					value='*'
					onClick={props.onSignClick}
					className={styles.primary__button}
				>
					x
				</button>
			</div>
			<div className={styles.result__buttons}>
				<button
					id='clear'
					onClick={props.onReset}
					className={styles.secondary__button}
				>
					Reset
				</button>
				<button
					id='equals'
					onClick={props.onCalculate}
					className={styles.tertiary__button}
				>
					=
				</button>
			</div>
		</div>
	);
};

export default Buttons;
